### ISSUE TITLE
Batterie leer error

### ISSUE THREAD

**Issue by danielegger1** [www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge#7]
The first message which get´s reported from Judo is always "Batterie leer", but my battery is on 100%, not sure how this can be cleared, because I believe the error comes from the system? I had the batteries disconnected some time ago, maybe the error is still present and needs to be cleared? Maybe you have a better idea than I do

![image](https://user-images.githubusercontent.com/16063664/215310668-5402bb63-1a4f-4593-ae9d-67573f6f71e3.png)
![image](https://user-images.githubusercontent.com/16063664/215310705-4b237ad7-c6c9-4574-9e43-2d3958cecdc9.png)
![image](https://user-images.githubusercontent.com/16063664/215310728-11c7591e-8399-46fb-a0ae-23214896e3a2.png)

**Comment by www-ShapeLabs-de** [comment]
The very first time the script is executed, the last error message from the error memory is output once. Thereby the error ID is stored in a file. This file will then be loaded when the script is started. Since this error ID was noted as published at the further starts of the script, the error is then no longer output.
